version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5500:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=1234
      - POSTGRESQL_DATABASE=task-mgt-app

volumes:
  postgresql_data:
